package day4;
class Resource{
	
}
class Abc{
	public void run() {
		int x=0;
		int y=10;
		int z=y/x;
		System.out.println(z);
	}
}

public class MyExcept {

	public static void main(String[] args) {
		try {
			new Abc().run();
		}
		catch(ArithmeticException e) {
			System.out.println(e.getMessage());
		}
		finally {
			System.out.println("Finally block");
		}
		
//		new Abc().run();
		System.out.println("This is the prog continuation..");
	}

}











package day4;
class Resource implements AutoCloseable{
	public void print(Object s) {
		System.out.println(s);
	}
	public void close() {
		System.out.println("Resource closed");
	}
}
class Calc{
	public int div(int x, int y) {
		int z=0;
		Resource r=new Resource();
		try {
			z=x/y;
			r.print(z);
		}
		catch(ArithmeticException e) {
			System.out.println(e);
			return 0;
		}
		finally {
		r.close();
		}
		return z;
		
	}
}

public class MyExcept {

	public static void main(String[] args) {
		Calc c=new Calc();
		c.div(100,0);
		System.out.println("This is the prog continuation..");
	}

}
















package day4;

import java.util.*;

class Resource implements AutoCloseable {
	public void print(Object s) {
		System.out.println(s);
	}

	public void close() {
		System.out.println("Resource closed");
	}
}

class Calc {
	public int div() {
		java.util.Scanner sc=new java.util.Scanner(System.in);
		int z=0;
		Resource r=new Resource();
		try {
			int x=sc.nextInt();
			int y=sc.nextInt();
			try {
				int[] a=new int[10];
				a[10]=20;
			}
			catch(ArrayIndexOutOfBoundsException e) {
				throw e;
			}
			z=x/y;
			r.print(z);
		}
		catch(ArithmeticException e) {
			System.out.println(e);
			return 0;
		}
		catch(InputMismatchException e) {
			System.out.println(e);
		}
		catch(Exception e) {
			System.out.println(e);
		}
		finally {
		r.close();
		}
		return z;
		
	}
}

public class MyExcept {
	public static void main(String[] args) {
		Calc c = new Calc();
		c.div();
		System.out.println("This is the prog continuation..");
	}
}




















package day4;
import java.io.*;

class Abc2{
	public void fn() throws IOException {
//		try {
		throw new IOException("Just to learn throws keyword");
//		}
//		catch(Exception e) {}
	}
}
class Abc3{
	void fnn() throws IOException {
		new Abc2().fn();
	}
}


public class MyExcept {
	public static void main(String[] args) {
		try {
			new Abc3().fnn();
		} catch (IOException e) {
			System.err.println(e);
			// TODO Auto-generated catch block
			//e.printStackTrace();
		}
		System.out.println("This is the prog continuation..");
	}
}















